BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXBBBBBBBB

BBBBB BBBBBBB

BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB

XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXX
            X XXXXXXXXXXXX XXXXX XXX XXXX XXXX XX XXXX XXXXXX XXXXXX XXXXXXXX XXXX XXXXXXX XXXXXX XXXXXXX XXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXX
    XXXXXX
XXXXXX

BBBB


XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX


      XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        BB BBBBBBBB
            BBB BBBBBBB BB BBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXX BB BBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXBBBBB XXXXXXXXXXXXX
                        BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX BBBBB
                        XXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            BBBBBB
        BBBBB
    XXXXXX
    
    
    
    XXXXXXXX
    
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXX
        XXX
    XXXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    
      XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
          XXXXXXXXXXXX XXXX XX XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX
  XXXXXX
XXXXXX
    
    BBBBB
BBBBBBBB