BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXXXXBBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB
          FFFFFF
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXX XX XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX

BBBBBBBB