

XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    BB BBBBBBBB
        BBB BBBBBBB BB BBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XX XXXXX XX XXX XXXXX XXX
                XXXX BB BBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXBBBBB XXXXXXXXXXXXX
                    BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX BBBBB
                    XXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        BBBBBB
    BBBBB
XXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXX XXX
        XX XXXXXX
    XXX
XXXXXXXXX
