XXXX XXXXXX XXXXXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXX
                XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                  XXXX X XXX XXXXXXXXXXXX
                XXXXXXX
              XXXX
              XX XXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                  XXXXX X XXXXXXXXXXXXXX
                XXXXXXX
              XXXX
            XXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXX
          XXXXXXX
          
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                  XX XXXXXXX
                XXXXXXX
              XXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                  XXXX

                  XXXXXX
                    BBBB BBBBBBBBBBBBBBBBBBBBBBB
                    BB BBBBBBBBBBB B B

                    XXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXX

                       XXXXX X
                      X

                    XXXXXXXXXXXX
                    BBBB

                  XXXXXXX
                    XXXX XXXX XX XXXXX
                    
                  XXXXXXXX

                    BBBBB
                    BBBBBBB
                  XXXXXXX

                XXXXXXX
              XXXX
            XXXXXX
          XXXXXX

        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXXXX
                XXXXXXXXXX
              XXXXXXX
            XXXX

            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXX XXXXXXXXX XXXXXXX
            XXXXXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXX XX
                XXX XXXXXXXXXXXXXXX XXXXXXXX
                  XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXX
                  XXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      BBB B BB BBBBBBBBBB
                          XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                      BBBBBB
                  XXXXXX
              XXXXX
              
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
              
              XXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX