BBBBBBB BBBBBBBBBBB

BBBBB BBBBBXXXXXXX XXXXXXBBBBBBBB

BBBBB BBBBBBB
    
  XXXX XXXXXXX XXXXXXX XXXXXXX XXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX
          XXXXXXX XXXXXXX
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXX
              XXXXXXXXXXXXXX 
            XXXXX
            XXX
                
                XXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXX
              
              BBBBBBBBBB
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #

    XXXXXX
 
  
  XXXX XXX XXXXXXX XXXXXXX XXXXXXX XXX
  BBBBBBBB