BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBB
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX X XXXXXXX
                    XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                BBBBBB
            XXXXX
            BB BBBBBBB BB BBBB
            XXXXXXXX XXX XXX XXXX XXXXXX XXXX XXXXX XXX XXXX XXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXX XXXXXXXXX X XXXXXXXXXXXX XXXXX XXX XXXX XXXX XX XXXX XXXXX XXXXXXXXXXXX
            XXXXXXX XXXXX XXXXXX XX X   XXXXX
            BBBB
            XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BBBBB
        XXXXXX
    XXXXXX

    XXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX
        BBBBBBBBBB
        XXXX XXXXXXXXXXXXX
            
        XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXX
XXXXXX
BBBBBBBB BBBBBBB