BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX
    BBBBBBBBBB
    FFFFFF
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
XXXXXXX
BBBBBBBB BBBBBBB