XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXX XX
            XXXXXXXX XX
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX XXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
        X
        XXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        XXXXXXX XX X
            XXXXXXX XX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X
        XXXXXXX X X
            XXXXXXX XXX XX
            XXXXXX XXXXX
        X
        XXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXXXXXX XXXX
        X
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX X X
            XXXXXXX XXX XX
            XXXXXX XXXXX
        X
        XXXXXXXXXXXX XXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXX XXX XXXXXXXXXXXX XX X
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXX
        X
        XXXXXXXXXXXX XX X
            XXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X
        XXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXX
        X
        XXXXXXX XXXXX X
            XXXXXX XXXXXX
            XXXXXXXXXXXX XXXXX
        X
        XXXXXXX XXXXXXX X
            XXXXXX XXXX
            XXXXXXXXXXXX XXXXX
        X
        XXXXXXX XXXXX X
            XXXXXXXXXX XXXXX
        X
        XXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXX
            XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
            XX XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                BBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
                XXXXXXX
                    XXXX
                        XXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXX
                        XXXXXXXXXXXXXX
                    XXXXX
                XXXXXXXX
                XXXXXXX
                    BBB BBBB BB BBBBBBBBBBBBBBB
                    XXXX
                        XXXXXXXXX
                        XXXXXXXXX
                        XXXXXXXXXX
                        XXXXXXXXXX
                    XXXXX
                    BBBBBB
                XXXXXXXX
            XXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXX
            XXXXXXXX XXXXXXX XXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX
            XXXXXXXX XXX XXX XXXX XXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXXX
XXXXXXX